name: "Build the executable"

on:
  push:
    branches:
      - "*"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true

      - name: install go deps
        run: sudo apt-get install -y mingw-w64

      - name: build the binary
        run: env CC=x86_64-w64-mingw32-gc GOOS=windows GOARCH=amd64 CGO_ENABLED=1 go build -o "DCS Updater.exe" -ldflags -H=windowsgui ./cmd/

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: store the binary 
        uses: actions/upload-artifact@v3
        with:
          name: "DCS Updater-${{ env.sha_short }}.exe"
          path: |
            "DCS Updater.exe"
            "DCS Updater.exe.manifest"
          retention-days: 7
      