name: "Build the executable..."

on:
  push:
    branches:
      - "*"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true

      - name: install go deps
        run: go mod tidy

      - name: build the binary
        run: env GOOS=windows GOARCH=amd64 go build -o "DCS Updater.exe" -ldflags -H=windowsgui ./cmd/

      - name: store the binary 
        uses: actions/upload-artifact@v3
        with:
          name: "DCS Updater-${{ steps.vars.outputs.short_sha }}.exe"
          path: "./DCS Updater.exe"
      