name: "Build the executable"

on:
  push:
    branches:
      - "*"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true

      - name: build the binary
        run: env GOOS=windows GOARCH=386 go build -o "DCS Updater.exe" -ldflags -H=windowsgui ./cmd/

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: store the binary 
        uses: actions/upload-artifact@v3
        with:
          name: "DCS Updater-${{ env.sha_short }}"
          path: "./DCS Updater.exe*"
          retention-days: 7
      